# Generated by Django 5.1.1 on 2024-09-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurucon', '0003_alter_schedule_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
    ]
