# Generated by Django 5.1.1 on 2024-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurucon', '0004_remove_schedule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
